version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1-VerySecure&
    ports:
      - 1433:1433
  redis:
    image: redis
    ports:
      - 6379:6379
  api:
    build:
      context: ./src
      dockerfile: ./Dockerfile
    # networks:
    #   - default
    image: alanmynah/url-shortener-csharp
    depends_on:
      - db
      - redis

# networks:
#   default:
#     name: url-shortener-csharp-network