version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1-VerySecure&
    ports:
      - 1433:1433
  redis:
    image: redis
    ports:
      - 6379:6379
  api:
    build:
      context: ./src
      dockerfile: ./Dockerfile
    image: alanmynah/url-shortener-csharp
    depends_on:
      - db
      - redis
    env_file:
      .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ~/.aspnet/https:/https:ro